# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            context: user
            form_login:
                provider: fos_userbundle
                login_path:   /user/login
                check_path:   /user/login-check
                failure_path: /user/login
                default_target_path: /user/dashboard
                use_forward:  false
                use_referer:  true

#                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                csrf_provider: form.csrf_provider

            logout:
                path:    /user/logout
                target:  warp_drive_security_login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

