warp_drive_user:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /


warp_drive_security_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: FOSUserBundle:Security:login


warp_drive_security_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: FOSUserBundle:Security:check

warp_drive_security_logout:
    path: /logout
    methods: [GET]
    defaults:
        _controller: FOSUserBundle:Security:logout

warp_drive_security_register:
    path: /register
    methods: [GET,POST]
    defaults:
        _controller: FOSUserBundle:Registration:register

